CREATE SEQUENCE MYCUSTOMER_ID_SEQ AS integer;


CREATE TABLE PUBLIC.MYCUSTOMER (
   CUSTOMER_ID integer NOT NULL DEFAULT nextval('MYCUSTOMER_ID_SEQ'),
   FIRST_NAME varchar(50),
   LAST_NAME varchar(50),
   EMAIL varchar(50)
);


ALTER SEQUENCE MYCUSTOMER_ID_SEQ OWNED BY MYCUSTOMER.CUSTOMER_ID;